'use client';
import {useState} from 'react';
import {ArrowRight,Check,Crown,ShoppingCart,Salad,Beef,Milk} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
import {proteins,sides,sauces,BowlConfig} from './bowl-data';
import {asset,money} from './data';
export function BowlBuilder({onAdd,go}:{onAdd:(b:BowlConfig)=>void;go:(r:string)=>void}){
const [protein,setProtein]=useState(0),[selected,setSelected]=useState([0,2,4]),[sauce,setSauce]=useState(0),[added,setAdded]=useState(false);
const options=(names:string[],prefix:string,value:number,set:(n:number)=>void)=><RadioGroup className="ingredient-grid" value={String(value)} onValueChange={v=>{set(Number(v));setAdded(false)}} aria-label={prefix==='protein'?'Proteína':'Vinagreta'}>{names.map((name,i)=><label className={'ingredient '+(value===i?'chosen':'')} key={name}><img src={asset(`bowl-${prefix}-${i}`)} alt=""/><b>{name}</b><RadioGroupItem value={String(i)} aria-label={name}/>{value===i&&<Check className="ingredient-check"/>}</label>)}</RadioGroup>;
const choices=[{name:proteins[protein],image:`protein-${protein}`},...selected.map(i=>({name:sides[i],image:`side-${i}`})),{name:sauces[sauce],image:`sauce-${sauce}`}];
return <main className="bowl-page"><section className="bowl-hero shell"><img className="bowl-hero-photo" src={asset('bowl-hero')} alt="Bowl de pollo, arroz y vegetales"/><div className="bowl-hero-copy"><span className="handwritten">MR. SHAKY <Crown/></span><h1>ARMA<br/><em>TU BOWL</em></h1><p>Tu comida,<br/><strong>a tu manera.</strong></p><div className="bowl-formula"><span><Beef/>TU PROTEÍNA</span><span><Salad/>3 ACOMPAÑANTES</span><span><Milk/>VINAGRETA</span></div></div><div className="bowl-price-sticker">DESDE<strong>$24.900</strong></div></section><div className="shell bowl-content"><section className="bowl-section"><div className="bowl-section-heading"><span>1</span><h2>Elige tu proteína</h2><small>1 opción obligatoria</small></div>{options(proteins,'protein',protein,setProtein)}</section><section className="bowl-section"><div className="bowl-section-heading"><span>2</span><h2>Elige 3 acompañantes</h2><small aria-live="polite">{selected.length} de 3 seleccionados</small></div><div className="ingredient-grid sides-grid" role="group" aria-label="Acompañantes">{sides.map((name,i)=><label key={name} className={'ingredient '+(selected.includes(i)?'chosen':'')+(selected.length===3&&!selected.includes(i)?' selection-full':'')}><img src={asset(`bowl-side-${i}`)} alt=""/><b>{name}</b><Checkbox aria-label={name} checked={selected.includes(i)} disabled={selected.length===3&&!selected.includes(i)} onCheckedChange={checked=>{setSelected(s=>checked?[...s,i]:s.filter(n=>n!==i));setAdded(false)}}/></label>)}</div><p className="bowl-help">Para cambiar un acompañante, desmarca uno de los seleccionados.</p></section><section className="bowl-section"><div className="bowl-section-heading"><span>3</span><h2>Elige tu vinagreta</h2><small>1 opción obligatoria</small></div>{options(sauces,'sauce',sauce,setSauce)}</section><section className="bowl-summary"><div><h2>Tu bowl</h2><div className="bowl-selection">{choices.map(c=><div key={c.image}><img src={asset('bowl-'+c.image)} alt=""/><span>{c.name}</span></div>)}</div></div><div className="bowl-total">Precio final<strong>{money(24900)}</strong></div><button disabled={selected.length!==3} className="yellow full" onClick={()=>{onAdd({protein,sides:[...selected].sort(),sauce});setAdded(true)}}><ShoppingCart/>Agregar al pedido <ArrowRight/></button>{added&&<button className="outline full" onClick={()=>go('pedido')}>Planificar mi pedido <ArrowRight/></button>}<p className="demo-note">Precio de referencia. Ingredientes, disponibilidad y valores nutricionales pendientes de validación.</p></section></div></main>}
