"use client";
import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowRight,ShoppingBag,Search,Heart,Dumbbell,Leaf,Timer,Calculator,CalendarDays,Utensils,Headphones,Menu,Home,BarChart3,Plus,Minus,Trash2,Check,Star,FlipHorizontal2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Checkbox} from '@/components/ui/checkbox';
import {Toaster,toast} from 'sonner';
import {products,categories,branches,spotifyPlaylistId,demoReviews,money,Product} from '@/lib/demo-data';
import {Macros,Choice} from './shaky-shared';
import {NutritionTools} from './shaky-tools';
type Cart=Record<string,number>;
type Order={id:string;branch:string;date:string;time:string;total:number;items:{name:string;qty:number}[]};
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export default function ShakyApp(){
 const [cart,setCart]=useState<Cart>({}),[favorites,setFavorites]=useState<string[]>([]),[loaded,setLoaded]=useState(false);
 const [toolOpen,setToolOpen]=useState('');
 const [cartOpen,setCartOpen]=useState(false),[navOpen,setNavOpen]=useState(false),[detail,setDetail]=useState<Product|null>(null);
 const [category,setCategory]=useState('Todos'),[query,setQuery]=useState(''),[favOnly,setFavOnly]=useState(false),[sort,setSort]=useState('featured');
 const [compare,setCompare]=useState<string[]>([]),[compareOpen,setCompareOpen]=useState(false),[expanded,setExpanded]=useState(false);
 const [branch,setBranch]=useState('poblado'),[date,setDate]=useState(''),[time,setTime]=useState(''),[order,setOrder]=useState<Order|null>(null),[orderOpen,setOrderOpen]=useState(false);
 const [reviews,setReviews]=useState(demoReviews),[reviewOpen,setReviewOpen]=useState(false),[reviewName,setReviewName]=useState(''),[reviewText,setReviewText]=useState(''),[stars,setStars]=useState('5');
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('shaky-demo-v1')||'{}');setCart(Object.fromEntries(Object.entries(saved.cart||{}).filter(([id,n])=>products.some(p=>p.id===id)&&Number.isInteger(n)&&Number(n)>0&&Number(n)<=99)) as Cart);setFavorites(Array.isArray(saved.favorites)?saved.favorites.filter((id:string)=>products.some(p=>p.id===id)):[]);if(Array.isArray(saved.reviews))setReviews([...demoReviews,...saved.reviews.filter((r:any)=>typeof r.name==='string'&&typeof r.text==='string'&&r.stars>=1&&r.stars<=5).slice(0,20)]);if(saved.order&&typeof saved.order.id==='string'&&Array.isArray(saved.order.items))setOrder(saved.order);}catch{}setDate(localDate());setLoaded(true)},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem('shaky-demo-v1',JSON.stringify({cart,favorites,reviews:reviews.filter(r=>!r.id.startsWith('r')),order}))}catch{}},[cart,favorites,reviews,order,loaded]);
 const add=(id:string)=>{setCart(c=>({...c,[id]:Math.min(99,(c[id]||0)+1)}));toast.success('Agregado a tu carrito',{description:products.find(p=>p.id===id)?.name})};
 const changeQty=(id:string,delta:number)=>setCart(c=>{const next={...c,[id]:Math.min(99,(c[id]||0)+delta)};if(next[id]<=0)delete next[id];return next});
 const toggleFavorite=(id:string)=>setFavorites(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id]);
 const toggleCompare=(id:string)=>{if(compare.includes(id))setCompare(compare.filter(x=>x!==id));else if(compare.length<3)setCompare([...compare,id]);else toast('Puedes comparar hasta 3 productos',{description:'Retira uno para elegir otro.'})};
 const count=Object.values(cart).reduce((a,b)=>a+b,0),total=products.reduce((sum,p)=>sum+(cart[p.id]||0)*p.price,0);
 let filtered=products.filter(p=>(!favOnly||favorites.includes(p.id))&&(category==='Todos'||p.category===category||(category==='Veggie'&&p.veggie)||(category==='Alto en proteína'&&p.protein>=25)||(category==='Bajo en carbohidratos'&&p.carbs<=25))&&(`${p.name} ${p.description}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase())));
 if(sort==='price')filtered=[...filtered].sort((a,b)=>a.price-b.price);if(sort==='protein')filtered=[...filtered].sort((a,b)=>b.protein-a.protein);
 const visible=expanded||query||category!=='Todos'||favOnly?filtered:filtered.slice(0,4);
 const goMenu=()=>{setNavOpen(false);document.getElementById('menu')?.scrollIntoView({behavior:'smooth'})};
 const goPlan=()=>{setCartOpen(false);document.getElementById('planifica')?.scrollIntoView({behavior:'smooth'})};
 const submitOrder=(e:React.FormEvent)=>{e.preventDefault();if(!count){toast('Agrega al menos un producto a tu carrito');goMenu();return}if(!date||!time||new Date(date+'T'+time).getTime()<Date.now()+30*60000){toast.error('Elige una hora con al menos 30 minutos de anticipación');return}const next:Order={id:'DEMO-'+Date.now().toString().slice(-6),branch:branches.find(b=>b.id===branch)!.name,date,time,total,items:products.filter(p=>cart[p.id]).map(p=>({name:p.name,qty:cart[p.id]}))};setOrder(next);setOrderOpen(true);setCart({});};
 const slots=Array.from({length:23},(_,i)=>`${String(10+Math.floor(i/2)).padStart(2,'0')}:${i%2?'30':'00'}`).filter(t=>date&&new Date(date+'T'+t).getTime()>Date.now()+30*60000);
 useEffect(()=>{if(time&&!slots.includes(time))setTime('')},[date,time,slots.join(',')]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();Promise.resolve(context.registerTool({name:'search_menu',title:'Buscar platos',description:'Filtra el catálogo visible por nombre o ingrediente. No crea pedidos.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:100}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:any)=>{if(!input||typeof input.query!=='string'||input.query.length>100)throw new Error('La búsqueda debe tener hasta 100 caracteres');setQuery(input.query);setCategory('Todos');setFavOnly(false);setExpanded(true);document.getElementById('menu')?.scrollIntoView();await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {query:input.query};}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[]);
 return <><Toaster richColors position="top-center"/><a className="skip" href="#menu">Ir al menú</a><header className="header wrap"><a href="#inicio" aria-label="Mr. Shaky, inicio"><span className="wordmark" role="img" aria-label="Mr. Shaky, marca del mockup proporcionado"/></a><nav><a href="#inicio">Inicio</a><a href="#menu">Menú</a><a href="#calculadoras" onClick={e=>{e.preventDefault();setToolOpen("calculadoras")}}>Calculadoras</a><a href="#planifica">Planifica</a><a href="#nosotros">Nosotros</a><a href="#comunidad">Comunidad</a></nav><div className="header-actions"><button aria-label="Buscar productos" onClick={()=>{goMenu();document.getElementById('search')?.focus({preventScroll:true})}}><Search/></button><button aria-label={`Abrir carrito, ${count} productos`} onClick={()=>setCartOpen(true)}><ShoppingBag/>{count>0&&<b className="badge">{count}</b>}</button><a className="btn" href="#menu">Haz tu pedido <ArrowUpRight size={18}/></a><button className="mobile-menu" aria-label="Abrir navegación" onClick={()=>setNavOpen(true)}><Menu/></button></div></header><main id="inicio">
 <section className="hero wrap"><div className="hero-copy"><div className="eyebrow">COMIDA REAL. OBJETIVOS REALES.</div><h1>ENTRENA.<br/>COME.<br/><em>LOGRA.</em></h1><p>Platos deliciosos, balanceados y listos<br/> cuando los necesitas.</p><div className="actions"><a className="btn" href="#menu">Haz tu pedido <ArrowUpRight size={20}/></a><a className="btn outline" href="#menu">Explorar menú</a></div><div className="benefits"><span><Leaf/>Ingredientes<br/> reales</span><span><Dumbbell/>Nutrición<br/> balanceada</span><span><Timer/>Listo en<br/> minutos</span><span><Heart/>Sabor sin<br/> culpa</span></div></div><div className="hero-art"><img src="/hero-bowl.png" alt="Gran bowl de pollo con arroz, aguacate y vegetales" fetchPriority="high"/><div className="hero-note">DISCIPLINA<br/>TAMBIÉN SE SABE<br/>DELICIOSA</div></div></section><div className="drip"/>
 <section className="quick light"><div className="wrap"><div className="section-head"><div><h2>¿QUÉ QUIERES HACER HOY?</h2><p>Tu rutina, tu comida, tu ritmo.</p></div><span className="eyebrow">HECHO PARA TI ↗</span></div><div className="quick-grid">{[[Calculator,'Calcula tus macros','Descubre lo que tu cuerpo necesita.','calculadoras'],[Dumbbell,'Encuentra tu plato','Cuéntanos qué entrenaste hoy.','quiz'],[CalendarDays,'Programa tu pedido','Tú entrenas. Nosotros cocinamos.','planifica'],[Utensils,'Explora el menú','Comer bien también sabe brutal.','menu']].map(([Icon,t,d,id]:any)=><a className="quick-card" href={'#'+id} key={id} onClick={e=>{if(id==="calculadoras"||id==="quiz"){e.preventDefault();setToolOpen(id)}}}><Icon/><ArrowUpRight className="corner"/><h3>{t}</h3><p>{d}</p></a>)}</div></div></section>
 <section className={`wrap section ${expanded||query||category!=='Todos'||favOnly?'show-all':''}`} id="menu"><div className="section-head"><div><div className="eyebrow">EL COMBUSTIBLE DE TUS METAS</div><h2>NUESTRO <em>MENÚ</em></h2><p>Ingredientes reales. Todo el sabor. Cero excusas.</p></div><button className="btn outline compare-button" onClick={()=>setCompareOpen(true)}><BarChart3 size={17}/>Comparar ({compare.length}/3)</button></div><div className="menu-controls"><div className="search-box"><Search size={18}/><input id="search" aria-label="Buscar en el menú" placeholder="¿Qué se te antoja?" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Limpiar búsqueda" onClick={()=>setQuery('')}>×</button>}</div><Choice label="Ordenar por" value={sort} onChange={setSort} options={[{value:'featured',label:'Recomendados'},{value:'price',label:'Menor precio'},{value:'protein',label:'Más proteína'}]}/><button className={'favorite-filter '+(favOnly?'active':'')} aria-pressed={favOnly} onClick={()=>setFavOnly(!favOnly)}><Heart size={18} fill={favOnly?'currentColor':'none'}/>Favoritos ({favorites.length})</button></div><div className="filters" aria-label="Categorías">{categories.map(c=><button key={c} aria-pressed={category===c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="products">{visible.map(p=><ProductCard key={p.id} p={p} favorite={favorites.includes(p.id)} compared={compare.includes(p.id)} onFavorite={()=>toggleFavorite(p.id)} onCompare={()=>toggleCompare(p.id)} onAdd={()=>add(p.id)} onDetail={()=>setDetail(p)}/>)}</div>{!visible.length&&<div className="empty"><Search/><h3>No encontramos ese antojo</h3><p>Prueba otra búsqueda o explora todos los platos.</p><button className="btn" onClick={()=>{setQuery('');setCategory('Todos');setFavOnly(false)}}>Ver todo el menú</button></div>}{filtered.length>4&&!expanded&&!query&&category==='Todos'&&!favOnly&&<button className="btn outline more" onClick={()=>setExpanded(true)}>Ver todo el menú <ArrowRight size={18}/></button>}<p className="fineprint catalog-note">Menú demo · Precios en COP · Fotografías ilustrativas · Macros y puntuaciones de ejemplo.</p></section>
 <a className="mobile-macros" href="#calculadoras" onClick={e=>{e.preventDefault();setToolOpen("calculadoras")}}><Calculator/><span><strong>Calcula tus macros</strong><small>Descubre cuánta proteína necesitas según tu rutina.</small></span><ArrowUpRight/></a>
 <section className="popular light"><div className="wrap popular-grid"><div className="compare-teaser"><span className="eyebrow">ELIGE CON TODO CLARO</span><h3>COMPARA<br/>TUS FAVORITOS</h3><p>Hasta 3 productos, lado a lado.</p><div className="mini-images">{products.slice(0,3).map(p=><span className={`food-sprite food-${p.id}`} role="img" aria-label={p.name} key={p.id}/>)}</div><button className="btn" onClick={()=>setCompareOpen(true)}>Comparar ahora <ArrowRight size={17}/></button></div>{[products[0],products[3]].map((p,i)=><div className={`popular-item popular-${p.id}`} key={p.id}><div><span className="eyebrow">{i?'EL SHAKE MÁS PEDIDO':'EL FAVORITO DEL MENÚ'}</span><h3>{i?'BEBIDA MÁS':'PRODUCTO MÁS'}<br/>POPULAR</h3><h4>{p.name}</h4><div className="rating">★★★★★ <span>{p.rating} ({p.reviews})</span></div><p>{i?'Tu dosis deliciosa de proteína.':'El favorito de la familia Shaky.'}</p><button className="btn dark" onClick={()=>setDetail(p)}>Ver detalle <ArrowUpRight size={17}/></button></div><span className={`popular-photo food-sprite food-${p.id}`} role="img" aria-label={p.name}/></div>)}</div></section>
 
 <section className="plan-section" id="planifica"><div className="wrap plan-grid"><div><div className="eyebrow"><CalendarDays size={18}/>A TU HORA. A TU RITMO.</div><h2>PLANIFICA TU PEDIDO</h2><p>Elige dónde y cuándo recoger. Nosotros ponemos el sabor.</p><form onSubmit={submitOrder}><div className="schedule-fields"><Choice label="Sucursal" value={branch} onChange={setBranch} options={branches.map(b=>({value:b.id,label:b.name}))}/><label className="field"><span>Fecha de recogida</span><input aria-label="Fecha de recogida" type="date" name="pickupDate" required min={localDate()} value={date} onInput={e=>setDate(e.currentTarget.value)} onChange={e=>setDate(e.target.value)}/></label><Choice label="Hora de recogida" value={time} onChange={setTime} options={slots.length?slots.map(t=>({value:t,label:t})):[{value:'unavailable',label:'Sin horarios hoy'}]}/></div><div className="schedule-bottom"><button className="btn" type="submit" disabled={!slots.length||!time||time==='unavailable'}>Programar pedido demo <ArrowUpRight size={18}/></button><button className="text-button" type="button" onClick={()=>setCartOpen(true)}>{count} productos · {money(total)} <ShoppingBag size={17}/></button></div><p className="fineprint">Demo sin cobro ni envío a la sucursal. Recogida de 10:00 a 21:00, con 30 minutos de anticipación.</p></form>{order&&<button className="last-order" onClick={()=>setOrderOpen(true)}><Check size={17}/>Ver último pedido demo · {order.id}</button>}</div><div className="plan-visual" role="img" aria-label="Entrenamiento y comida, imagen del mockup proporcionado"/></div></section><div className="drip"/>
 <section className="community light" id="comunidad"><div className="wrap community-grid"><div><div className="section-head"><div><div className="tool-heading"><Headphones/><span className="eyebrow">DALE PLAY A TU RUTINA</span></div><h2>MURO MUSICAL</h2><p>La comida está lista. Que suene tu próxima repetición.</p></div></div>{spotifyPlaylistId?<iframe title="Playlist oficial de Mr. Shaky en Spotify" className="spotify-frame" src={`https://open.spotify.com/embed/playlist/${spotifyPlaylistId}`} allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"/>:<div className="music-card"><div className="music-art"><Headphones size={55}/></div><div><span className="eyebrow">MR. SHAKY GYM MIX</span><h3>Tu energía<br/>tiene soundtrack.</h3><p>La playlist oficial llegará pronto.</p><a href="https://open.spotify.com/search/workout/playlists" target="_blank" rel="noreferrer" className="btn">Explorar Spotify <ArrowUpRight size={17}/></a></div></div>}</div><div><div className="section-head"><div><h2>LA FAMILIA SHAKY</h2><p>Opiniones de ejemplo · {(reviews.reduce((a,r)=>a+r.stars,0)/reviews.length).toFixed(1)} / 5</p></div><button className="review-link" onClick={()=>setReviewOpen(true)}>Ver todas <ArrowUpRight size={16}/></button></div><div className="review-grid">{reviews.slice(-2).map(r=><Review key={r.id} r={r}/>)}</div><button className="text-button" onClick={()=>setReviewOpen(true)}>Deja tu opinión <ArrowRight size={17}/></button></div></div></section>
 <section className="brand-banner" id="nosotros"><div className="wrap"><div><span className="eyebrow">SOMOS MR. SHAKY NUTRIBAR</span><h2>COMIDA QUE IMPULSA PERSONAS.</h2><p>Nos mueve lo mismo que a ti: comer rico, entrenar y disfrutar el camino.</p></div><a href="#menu" className="btn dark">Haz tu pedido <ArrowUpRight size={18}/></a></div></section><footer className="wrap"><a href="#inicio"><img src="/logo.png" alt="Mr. Shaky Nutribar"/></a><p>Comida real para<br/>gente que entrena.</p><div><a href="#menu">Menú</a><a href="#calculadoras" onClick={e=>{e.preventDefault();setToolOpen("calculadoras")}}>Calculadoras</a><a href="#planifica">Planifica</a><a href="#comunidad">Comunidad</a></div><span>Frontend de demostración<br/>© {new Date().getFullYear()} Mr. Shaky Nutribar</span></footer></main>
 <nav className="bottom-nav" aria-label="Navegación móvil"><a href="#inicio"><Home/><span>Inicio</span></a><a href="#menu"><Utensils/><span>Menú</span></a><button onClick={()=>setCartOpen(true)}><ShoppingBag/><span>Carrito{count?` (${count})`:''}</span></button><a href="#planifica"><CalendarDays/><span>Pedido</span></a><a href="#comunidad"><Headphones/><span>Comunidad</span></a></nav>
 <Sheet open={navOpen} onOpenChange={setNavOpen}><SheetContent className="shaky-sheet"><SheetTitle>Navega a tu ritmo</SheetTitle><SheetDescription>Todo Mr. Shaky, en un lugar.</SheetDescription><div className="mobile-links">{[['Inicio','inicio'],['Menú','menu'],['Calculadoras','calculadoras'],['Quiz rápido','quiz'],['Planifica','planifica'],['Nosotros','nosotros'],['Comunidad','comunidad']].map(([t,id])=><a key={id} href={'#'+id} onClick={e=>{setNavOpen(false);if(id==="calculadoras"||id==="quiz"){e.preventDefault();setToolOpen(id)}}}>{t}<ArrowUpRight/></a>)}</div></SheetContent></Sheet>
 <Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetContent className="shaky-sheet cart-sheet"><SheetTitle>TU CARRITO <em>({count})</em></SheetTitle><SheetDescription>Tu próxima comida empieza aquí. Precios en COP.</SheetDescription>{!count?<div className="empty"><ShoppingBag size={45}/><h3>Tu carrito tiene hambre.</h3><p>Encuentra tu próximo favorito en el menú.</p><button className="btn" onClick={()=>{setCartOpen(false);goMenu()}}>Explorar menú</button></div>:<><div className="cart-items">{products.filter(p=>cart[p.id]).map(p=><div className="cart-item" key={p.id}><span className={`food-sprite cart-photo food-${p.id}`} role="img" aria-label={p.name}/><div><h3>{p.name}</h3><p>{money(p.price)}</p><div className="quantity"><button aria-label={'Quitar una unidad de '+p.name} onClick={()=>changeQty(p.id,-1)}><Minus size={15}/></button><output>{cart[p.id]}</output><button disabled={cart[p.id]>=99} aria-label={'Añadir una unidad de '+p.name} onClick={()=>changeQty(p.id,1)}><Plus size={15}/></button></div></div><button className="delete" aria-label={'Eliminar '+p.name} onClick={()=>setCart(c=>{const next={...c};delete next[p.id];return next})}><Trash2 size={18}/></button></div>)}</div><div className="cart-summary"><div><span>Total</span><strong>{money(total)}</strong></div><p>Recogida en sucursal · Sin costo de envío</p><button className="btn" onClick={goPlan}>Elegir hora de recogida <ArrowRight size={18}/></button><span className="fineprint">Demo: no se realizan cobros ni pedidos reales.</span></div></>}</SheetContent></Sheet>
 <Dialog open={!!toolOpen} onOpenChange={open=>!open&&setToolOpen('')}><DialogContent className="shaky-dialog tool-dialog" data-tool={toolOpen}><DialogTitle className="sr-only">{toolOpen==='quiz'?'Encuentra tu plato':'Calcula tus macros'}</DialogTitle><DialogDescription className="sr-only">Herramientas orientativas de Mr. Shaky.</DialogDescription><NutritionTools add={add}/></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={open=>!open&&setDetail(null)}><DialogContent className="shaky-dialog detail-dialog"><DialogTitle>{detail?.name}</DialogTitle><DialogDescription>Ingredientes y nutrición de ejemplo por porción.</DialogDescription>{detail&&<><div className={`detail-image food-sprite food-${detail.id}`} role="img" aria-label={detail.name}/><p>{detail.description}</p><Macros p={detail}/><p className="fineprint">{detail.allergens} Las fotografías son ilustrativas; confirma la receta y los alérgenos con la sucursal.</p><div className="product-bottom"><strong>{money(detail.price)}</strong><button className="btn" onClick={()=>add(detail.id)}>Agregar al carrito +</button></div><div className="rating">★★★★★ <span>{detail.rating} · {detail.reviews} puntuaciones demo</span></div></>}</DialogContent></Dialog>
 <Dialog open={compareOpen} onOpenChange={setCompareOpen}><DialogContent className="shaky-dialog compare-dialog"><DialogTitle>COMPARA TUS FAVORITOS</DialogTitle><DialogDescription>Selecciona hasta 3 productos en las tarjetas del menú.</DialogDescription>{compare.length?<><div className="compare-table"><table><thead><tr><th>Por porción</th>{compare.map(id=>{const p=products.find(p=>p.id===id)!;return <th key={id}><div className={`food-sprite compare-photo food-${p.id}`}/><span>{p.name}</span><button onClick={()=>toggleCompare(id)} aria-label={'Retirar '+p.name}>Retirar ×</button></th>})}</tr></thead><tbody>{[['protein','Proteína','g'],['carbs','Carbohidratos','g'],['fat','Grasas','g'],['calories','Energía','kcal'],['price','Precio','']].map(([key,label,unit])=><tr key={key}><th>{label}</th>{compare.map(id=>{const p=products.find(p=>p.id===id)!;return <td key={id}>{key==='price'?money(p.price):`${p[key as 'protein']} ${unit}`}</td>})}</tr>)}<tr><th>Tu elección</th>{compare.map(id=><td key={id}><button className="btn" onClick={()=>add(id)}>Agregar +</button></td>)}</tr></tbody></table></div><button className="text-button" onClick={()=>{setCompareOpen(false);goMenu()}}>Elegir otro producto <ArrowRight size={17}/></button></>:<div className="empty"><BarChart3 size={40}/><p>Marca «Comparar» en tus productos favoritos.</p><button className="btn" onClick={()=>{setCompareOpen(false);goMenu()}}>Elegir productos</button></div>}</DialogContent></Dialog>
 <Dialog open={orderOpen} onOpenChange={setOrderOpen}><DialogContent className="shaky-dialog"><DialogTitle>¡PEDIDO DEMO PROGRAMADO!</DialogTitle><DialogDescription>Esta es una simulación. No se envió a la sucursal ni se realizó ningún cobro.</DialogDescription>{order&&<div className="order-confirm"><div className="success-icon"><Check/></div><h3>{order.id}</h3><p>{order.branch}<br/>{order.date} · {order.time}</p><ul>{order.items.map(i=><li key={i.name}>{i.qty} × {i.name}</li>)}</ul><strong>Total: {money(order.total)}</strong><button className="btn" onClick={()=>setOrderOpen(false)}>Listo <Check size={18}/></button></div>}</DialogContent></Dialog>
 <Dialog open={reviewOpen} onOpenChange={setReviewOpen}><DialogContent className="shaky-dialog review-dialog"><DialogTitle>OPINIONES DE LA FAMILIA</DialogTitle><DialogDescription>Reseñas demo. Tu opinión se guarda solo en este navegador.</DialogDescription><div className="all-reviews">{reviews.map(r=><Review key={r.id} r={r}/>)}</div><form className="review-form" onSubmit={e=>{e.preventDefault();if(!reviewName.trim()||!reviewText.trim())return;setReviews([...reviews,{id:'local-'+Date.now(),name:reviewName.trim(),text:reviewText.trim(),stars:Number(stars)}]);setReviewName('');setReviewText('');toast.success('Opinión guardada en este navegador')}}><h3>Cuéntanos qué te pareció</h3><label className="field"><span>Nombre</span><input required maxLength={40} value={reviewName} onChange={e=>setReviewName(e.target.value)}/></label><Choice label="Puntuación" value={stars} onChange={setStars} options={[5,4,3,2,1].map(n=>({value:String(n),label:`${n} ${n===1?'estrella':'estrellas'}`}))}/><label className="field full"><span>Tu opinión</span><textarea required minLength={8} maxLength={500} value={reviewText} onChange={e=>setReviewText(e.target.value)}/></label><button className="btn" type="submit">Guardar opinión</button></form></DialogContent></Dialog>
 </>
}
function ProductCard({p,favorite,compared,onFavorite,onCompare,onAdd,onDetail}:{p:Product;favorite:boolean;compared:boolean;onFavorite:()=>void;onCompare:()=>void;onAdd:()=>void;onDetail:()=>void}){const [flipped,setFlipped]=useState(false);return <article className="product"><div className="product-flip"><button className={'flip-btn '+(flipped?'chosen':'')} aria-label={(flipped?'Ver detalle de ':'Ver macros de ')+p.name} aria-pressed={flipped} onClick={()=>setFlipped(!flipped)}><FlipHorizontal2 size={18}/></button><div className={'product-flip-inner'+(flipped?' flipped':'')}><div className="product-face product-front"><div className="product-photo"><button className="photo-button" aria-label={'Ver detalle de '+p.name} onClick={onDetail}><span className={`product-image food-sprite food-${p.id}`} role="img" aria-label={p.name}/></button><button className={'heart '+(favorite?'chosen':'')} aria-label={(favorite?'Quitar de':'Guardar en')+' favoritos: '+p.name} aria-pressed={favorite} onClick={onFavorite}><Heart size={20} fill={favorite?'currentColor':'none'}/></button><span className="protein-tag">{p.protein} g proteína</span></div><div className="product-body"><button className="product-title" onClick={onDetail}><h3>{p.name}</h3></button><p>{p.description}</p><div className="rating" aria-label={`${p.rating} de 5, ${p.reviews} reseñas de ejemplo`}>★★★★★ <span>{p.rating} ({p.reviews})</span></div><div className="product-bottom"><strong>{money(p.price)}</strong><button className="round" aria-label={'Agregar '+p.name} onClick={onAdd}><Plus size={20}/></button></div><label className="compare-check"><Checkbox checked={compared} onCheckedChange={onCompare} aria-label={'Comparar '+p.name}/>Comparar</label></div></div><div className="product-face product-back"><div className="product-back-body"><span className="eyebrow">MACROS POR PORCIÓN</span><h3>{p.name}</h3><Macros p={p}/><div className="product-bottom"><strong>{money(p.price)}</strong><button className="round" aria-label={'Agregar '+p.name} onClick={onAdd}><Plus size={20}/></button></div></div></div></div></div></article>}
function Review({r}:{r:{name:string;stars:number;text:string}}){return <article className="review"><div className="rating" aria-label={`${r.stars} de 5 estrellas`}>{'★'.repeat(r.stars)}{'☆'.repeat(5-r.stars)}</div><p>“{r.text}”</p><div className="review-person"><span>{r.name.charAt(0)}</span><strong>{r.name}</strong></div></article>}
